name: ✨ Feature Request
description: Suggest a new feature for the Temperature Control System
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees:
  - NiX-TbY

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature would be useful for the temperature control system
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Hardware Support (new sensors, displays, etc.)
        - User Interface (display, web interface)
        - Control Algorithm (PID, scheduling, etc.)
        - Connectivity (WiFi, Bluetooth, IoT)
        - Safety & Monitoring
        - Data Logging & Analytics
        - Configuration & Setup
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or use case this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: Describe how you'd like this feature to work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe alternative solutions you've considered...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        - Hardware requirements
        - Software changes needed
        - Library dependencies
        - Configuration changes

  - type: checkboxes
    id: complexity
    attributes:
      label: Implementation Complexity
      description: How complex do you think this feature would be?
      options:
        - label: Simple (minor code changes)
        - label: Medium (moderate development effort)
        - label: Complex (significant development effort)

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that would be helpful...
