name: ESP32-S3-Temperature-Control

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
        cache: "pip"

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio
          ~/.cache/pip
        key: ${{ runner.os }}-platformio-${{ hashFiles('my-arduino-project/platformio.ini') }}

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build Firmware
      working-directory: my-arduino-project
      run: |
        pio run --verbose

    - name: Prepare Build Artifacts
      working-directory: my-arduino-project
      run: |
        mkdir -p ../build-artifacts
        cp .pio/build/esp32-s3-devkitc-1/firmware.bin ../build-artifacts/ || echo "firmware.bin not found"
        cp .pio/build/esp32-s3-devkitc-1/firmware.elf ../build-artifacts/ || echo "firmware.elf not found"
        echo "Build Date: $(date)" > ../build-artifacts/build-info.txt
        echo "Commit: ${{ github.sha }}" >> ../build-artifacts/build-info.txt

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-s3-firmware-${{ github.sha }}
        path: build-artifacts/
        retention-days: 30

    - name: Run Tests (Optional)
      working-directory: my-arduino-project
      run: |
        if [ -d "test" ] && [ "$(ls -A test 2>/dev/null)" ]; then
          pio test --verbose
        else
          echo "No tests found, skipping..."
        fi
      continue-on-error: true


